### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [wiseaidev/polars-ai#2]
- [ ] Plots using plotters.
- [ ] Execute Code (there is a limitation since the OpenAI model used is trained on an old Polars version).
- [ ] Support more AI models.
